// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmsSablon.Data;

#nullable disable

namespace SmsSablon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250617101406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmsSablon.Models.Info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<int>("SmsHeaderId")
                        .HasColumnType("integer");

                    b.Property<string>("SmsText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SmsHeaderId");

                    b.ToTable("Infos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsLocked = false,
                            SmsHeaderId = 1,
                            SmsText = "Yarın tatil!",
                            TemplateName = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            IsLocked = true,
                            SmsHeaderId = 1,
                            SmsText = "Yeni etkinlik var",
                            TemplateName = "Etkinlik"
                        },
                        new
                        {
                            Id = 3,
                            IsLocked = false,
                            SmsHeaderId = 2,
                            SmsText = "Sistem bakımı yapılacak.",
                            TemplateName = "Teknik"
                        });
                });

            modelBuilder.Entity("SmsSablon.Models.SmsHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SmsHeaders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Header = "Duyuru"
                        },
                        new
                        {
                            Id = 2,
                            Header = "Bilgilendirme"
                        });
                });

            modelBuilder.Entity("SmsSablon.Models.Info", b =>
                {
                    b.HasOne("SmsSablon.Models.SmsHeader", "SmsHeader")
                        .WithMany("Infos")
                        .HasForeignKey("SmsHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmsHeader");
                });

            modelBuilder.Entity("SmsSablon.Models.SmsHeader", b =>
                {
                    b.Navigation("Infos");
                });
#pragma warning restore 612, 618
        }
    }
}
